[package]
name = "assets_json"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
plugin_macro = { path = "../../plugin_macro" }
serde_json = "1"
ctor = "0.2"
module_utils = { path = "../../module_utils" }