[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0"
chrono = "0.4"
axum = "0.7"
plugin_macro = { path = "../../plugin_macro" }
serde = { version = "1.0", features = ["derive"] }
ctor = "0.2"
