[package]
name = "greetings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
plugin_macro = { path = "../../plugin_macro" }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
ctor = "0.2"