[package]
name = "plugin_macro"
version = "0.2.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2", features = ["full", "extra-traits", "parsing"] }
proc-macro2 = "1"
serde_json = "1.0"
